---
services:
  - name: "NetworkManager"
    mandatory: true
  - name: "bluetooth"
    mandatory: false
  - name: "sddm"
    mandatory: true
  - name: "fstrim.timer"
    mandatory: false
  - name: "reflector.timer"
    mandatory: false

targets:
  - name: "graphical"
    mandatory: true
