---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - wheel
    - video
    - audio
    - storage
    - optical
    - network
    - power
autologinGroup: autologin
sudoersGroup: wheel
setRootPassword: true
doAutologin: false
passwordRequirements:
    minLength: 1
    maxLength: -1
allowWeakPasswords: true
allowWeakPasswordsDefault: false
userShell: /usr/bin/fish
